# -*- coding: utf-8 -*-
"""Run_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DC3gMbPt9XCTMhyYuo_eVxscY7q9VPAG

# This script loads in the clean data, runs preprocessing with EDA, and a logistic regression for the discrimination of real vs. fake news CS3.

##  Loading in packages and data.
"""

# Start by importing necessary packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import classification_report, confusion_matrix
import os

# If you are using Google Colab, mount to your Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Update the path to the correct folder
path_to_DS_4002_folder = '/content/drive/MyDrive/DS-4002'
os.chdir(path_to_DS_4002_folder)

# Read in the data set
fake = pd.read_csv("Fake.csv")
true = pd.read_csv("True.csv")

"""## Preprocessing"""

# Add classification labels
fake["label"] = 1
true["label"] = 0

# Combine data sets into one dataframe
df = pd.concat([fake, true], ignore_index=True)

# Since we are only focusing on headline text and label, we can remove everything else
df = df[["title", "label"]]

# We can also remove any missing headlines
df["title"] = df["title"].astype(str)
df = df[df["title"].str.strip() != ""]

# Now we can take a look at the data set
print(df.shape)
print(df["label"].value_counts())
df.head()

# We can then save this as a clean dataset to use for modeling
df.to_csv("headlines_clean.csv", index=False)

# Reload dataset to confirm structure
clean = pd.read_csv("headlines_clean.csv")
clean.columns, clean["label"].value_counts()

"""## Run EDA"""

# Start by visualizing the distribution of subjects in real vs. fake news headlines
# See what values there are for subject (true news)
true['subject'].unique()
true_subject_frequencies = true['subject'].value_counts()
true_subject_frequencies
# Plot value counts directly as a pie chart
true_subject_frequencies.plot(kind='pie', autopct='%1.1f%%', title='Distribution of Subjects (True News)')
plt.ylabel('')

plt.savefig('Distribution_of_Subjects_True.png',
            dpi=300,
            bbox_inches='tight',
            pad_inches=0.25
           )
plt.show()

# Now we can calculate the length of each headline (fake and true)
true_len = true['title'].str.len()
fake_len = fake['title'].str.len()
# Create histogram
plt.style.use('ggplot')
# Create figure and a set of subplots (1 row, 2 columns)
fig, axes = plt.subplots(1, 2, figsize=(10, 4), sharey=True)

axes[0].hist(true_len.dropna(), bins=30, edgecolor='black')
axes[0].set_title('True Headline Title Length\n(in Characters) Frequency')

axes[1].hist(fake_len.dropna(), bins=30, edgecolor='black')
axes[1].set_title('Fake Headline Title Length\n(in Characters) Frequency')

true_len = true.astype(str).apply(lambda col: col.str.len())
fake_len = fake.astype(str).apply(lambda col: col.str.len())

# Add padding so that titles don't overlap
fig.tight_layout(w_pad=6)

# Save it so that GitHub doesn't crop it
fig.savefig(
    'Distribution_of_Headline_Lengths.png',
    dpi=300,
    bbox_inches='tight',
    pad_inches=0.25
)

plt.show()

"""You can run other forms of EDA too.

## Run the Logistic Regression
"""

# Split the data into training and testing sets with balanced labels
X = clean["title"]
y = clean["label"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

# Create TF-IDF + Logistic Regression model pipeline
model = Pipeline([
    ("tfidf", TfidfVectorizer(stop_words="english")),
    ("lr", LogisticRegression(max_iter=1000))
])

# Train the model
model.fit(X_train, y_train);

# Generate the predictions and compute evaluation metrics
best_model = model

y_pred = best_model.predict(X_test)

acc = accuracy_score(y_test, y_pred)
prec = precision_score(y_test, y_pred)
rec = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print(f"Accuracy:  {acc:.4f}")
print(f"Precision: {prec:.4f}")
print(f"Recall:    {rec:.4f}")
print(f"F1 score:  {f1:.4f}")

print("\nClassification report:\n")
print(classification_report(y_test, y_pred, target_names=["Real", "Fake"]))

# Create the confusion matrix to show prediction outcomes
cm = confusion_matrix(y_test, y_pred)

cm_df = pd.DataFrame(
    cm,
    index=["Actual Real", "Actual Fake"],
    columns=["Predicted Real", "Predicted Fake"]
)

print("Confusion matrix:")
print(cm_df)